# Generated by Django 6.0.6 on 2026-06-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(default=1)),
                ('producto_id', models.IntegerField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('usuario_id', 'producto_id')},
            },
        ),
    ]
